baseURL = 'https://akkervarken.be'
languageCode = 'nl-be'
title = 'Akkervarken.be - Varkensvlees van regeneratieve landbouw'
theme = 'minimal'
copyright = '© 2025 Akkervarken.be - Pilcrow BV'
enableRobotsTXT = true

[params]
  description = 'Varkensvlees van varkens uit regeneratieve landbouw. Varkens die 100% buiten leven met veel ruimte en lokaal, duurzaam voeder. Vers en diepvries. Bestel online uw vleespakketten.'
  author = 'Mathias en Jolien'
  keywords = ['varkensvlees', 'boerderij', 'lokaal vlees', 'duurzaam vlees', 'Opwijk', 'akkervarkens', 'biologisch vlees', 'scharrelvlees', 'Vlaanderen']
  images = ['/img/slide1.jpg']
  # Google Analytics Measurement ID (format: G-XXXXXXXXXX)
  # Replace with your actual GA4 measurement ID to enable tracking
  googleAnalytics = 'G-51L2822M52'

[params.social]
  email = 'info@akkervarken.be'
  phone = '+32494185076'

[params.location]
  name = 'Akkervarken.be'
  address = 'Wolfstede 7'
  city = 'Opwijk'
  postalCode = '1745'
  country = 'België'
  latitude = '50.9666'
  longitude = '4.1833'

[taxonomies]
  tag = 'tags'
  category = 'categories'

[imaging]
  quality = 75
  resampleFilter = "Lanczos"

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false

[minify.tdewolff.html]
  keepWhitespace = false

[minify.tdewolff.css]
  keepCSS2 = false

[minify.tdewolff.js]
  keepVarNames = false
